# Generated by Django 2.1.7 on 2019-05-14 06:20

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('news_id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('news_title', models.CharField(max_length=20, verbose_name='标题')),
                ('news_author', models.CharField(max_length=10, verbose_name='作者')),
                ('news_briefr', models.CharField(max_length=20, verbose_name='简介')),
                ('news_content', ckeditor_uploader.fields.RichTextUploadingField(default='')),
                ('news_uploaddate', models.DateTimeField(verbose_name='上传时间')),
                ('news_clickNum', models.IntegerField(default=0, verbose_name='点击量')),
            ],
        ),
    ]
