# Generated by Django 2.1.7 on 2019-03-02 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Novel',
            fields=[
                ('novel_id', models.AutoField(primary_key=True, serialize=False)),
                ('novel_name', models.CharField(max_length=20)),
                ('novel_author', models.CharField(max_length=5)),
                ('novel_state', models.BooleanField()),
                ('novel_brief', models.TextField(blank=True)),
                ('novel_pic', models.ImageField(upload_to='pictures/novel_pic/%Y/%m/%d/')),
                ('novel_collectnum', models.IntegerField()),
                ('novel_grade', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='NovelChapter',
            fields=[
                ('nchapter_id', models.AutoField(primary_key=True, serialize=False)),
                ('nchapter_name', models.CharField(max_length=15)),
                ('nchapter_content', models.TextField(default='')),
                ('novel_name', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='novel.Novel')),
            ],
        ),
        migrations.CreateModel(
            name='NovelType',
            fields=[
                ('noveltype_id', models.AutoField(primary_key=True, serialize=False)),
                ('noveltype_name', models.CharField(max_length=5)),
            ],
        ),
        migrations.AddField(
            model_name='novel',
            name='novel_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novel.NovelType'),
        ),
    ]
