# Generated by Django 2.1.7 on 2019-03-02 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='novelchapter',
            name='nchapter_updatetime',
            field=models.DateField(auto_now=True),
        ),
    ]
