# Generated by Django 2.1.7 on 2019-03-02 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0002_novelchapter_nchapter_updatetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novel',
            name='novel_pic',
            field=models.ImageField(upload_to='novel_pic/%Y/%m/%d/'),
        ),
    ]
