# Generated by Django 2.1.7 on 2019-03-02 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0003_auto_20190302_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novel',
            name='novel_pic',
            field=models.ImageField(upload_to='pictures/novel_pic/%Y/%m/%d/'),
        ),
    ]
