# Generated by Django 2.1.7 on 2019-03-24 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0004_auto_20190302_1542'),
    ]

    operations = [
        migrations.RenameField(
            model_name='novelchapter',
            old_name='novel_name',
            new_name='novel',
        ),
    ]
