# Generated by Django 2.1.7 on 2019-03-02 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_in_id',
            field=models.IntegerField(default='1'),
        ),
    ]
