# Generated by Django 2.1.7 on 2019-04-08 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0003_auto_20190302_1659'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collect',
            old_name='user_id',
            new_name='user',
        ),
    ]
