# Generated by Django 2.1.7 on 2019-04-09 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0005_remove_collect_collect_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='collect',
            name='collect_name',
            field=models.CharField(default='', max_length=20, verbose_name='标题'),
        ),
    ]
