# Generated by Django 2.1.7 on 2019-03-02 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comic',
            fields=[
                ('comic_id', models.AutoField(primary_key=True, serialize=False)),
                ('comic_name', models.CharField(max_length=20)),
                ('comic_state', models.BooleanField()),
                ('comic_author', models.CharField(max_length=10)),
                ('comic_brief', models.TextField(blank=True)),
                ('comic_pic', models.ImageField(upload_to='pictures/comic_pic/%Y/%m/%d')),
                ('comic_collectnum', models.IntegerField()),
                ('comic_grade', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ComicType',
            fields=[
                ('comictype_id', models.AutoField(primary_key=True, serialize=False)),
                ('comictype_name', models.CharField(max_length=5)),
            ],
        ),
        migrations.AddField(
            model_name='comic',
            name='comic_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comic.ComicType'),
        ),
    ]
