# Generated by Django 2.1.7 on 2019-03-02 07:42

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComicChapter',
            fields=[
                ('cchapter_id', models.AutoField(primary_key=True, serialize=False)),
                ('cchapter_name', models.CharField(max_length=15)),
                ('cchapter_content', ckeditor_uploader.fields.RichTextUploadingField(default='')),
                ('cchapter_updatetime', models.DateField(auto_now=True)),
                ('comic_name', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='comic.Comic')),
            ],
        ),
    ]
