# Generated by Django 2.1.7 on 2019-03-25 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0002_comicchapter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comicchapter',
            old_name='comic_name',
            new_name='comic',
        ),
    ]
