# Generated by Django 2.1.7 on 2019-04-03 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user_id',
            new_name='cuser_id',
        ),
    ]
